image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - dockerize
  - deploy

build:
  stage: build
  image: maven:3-jdk-8-alpine
  script:
    - mvn package -B
  artifacts:
    paths:
      - target/*.jar

dockerize:
  stage: dockerize
  script:
    - docker version
    - docker build -t registry.gitlab.com/vibent/vibent-back .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker images
    - docker push registry.gitlab.com/vibent/vibent-back
  only:
    - master