image: docker:latest
services:
  - docker:18.06.0-dind

cache:
  paths:
  - .m2/repository


variables:
  DOCKER_DRIVER: overlay
  CONTAINER_URL: registry.gitlab.com
  CONTAINER_PATH: /vibent/vibent-back
  CONTAINER_IMAGE: ${CONTAINER_URL}${CONTAINER_PATH}
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - dockerize
  - deploy

build:
  stage: build
  image: maven:3.5.4-jdk-8-alpine
  script:
    - mvn package -B
  artifacts:
    paths:
      - target/*.jar

dockerize:
  stage: dockerize
  only:
    - master
  script:
    - echo $CONTAINER_IMAGE
    - docker version
    - docker build -t $CONTAINER_URL .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_URL
    - docker images
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE:latest

deploy:
  stage: deploy
  only:
    - master
  script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - curl -X POST -d '{"token":"#DZQ#phEGzj3C5s","restart":"vibent-back"}' https://admin.dev.vibent.com
