image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - dockerize
  - deploy

deploy:
  stage: deploy
  image: python:3-alpine
  variables:
    AWS_DEFAULT_REGION: "eu-west-3"
  before_script:
##### Install the AWS ECS-CLI #####
    - apk add --update curl
    - curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
    - chmod +x /usr/local/bin/ecs-cli
    - echo "Running script withs params $AWS_DEFAULT_REGION -  $AWS_ACCESS_KEY_ID - $AWS_SECRET_ACCESS_KEY - $PROD_TARGET_GROUP_ARN"
  script:
##### Configure ECS-CLI, run the container and scale to 2 #####
    - ecs-cli configure profile --profile-name vibent-gitlab-ci --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY
    - ecs-cli configure --region $AWS_DEFAULT_REGION --cluster Vibent
    - ecs-cli up --capability-iam --size 2 --instance-type t2.micro --vpc vpc-7a5dc513 --subnets subnet-3f2c8044,subnet-86a134ef --keypair $AWS_KEYPAIR --force
##### This docker-compose.yml is the one described above #####
    - ecs-cli compose --file docker-compose.yml service up --target-group-arn $PROD_TARGET_GROUP_ARN --container-name vibent-back --container-port 80
    - ecs-cli compose --file docker-compose.yml service scale 1
  environment:
    name: ci
    url: $PROD_LOAD_BALANCER_URL
  only:
    - master