image: docker:latest
services:
- docker:18.06.0-dind

variables:
  DOCKER_DRIVER: overlay
  CONTAINER_URL: registry.gitlab.com
  CONTAINER_PATH: /vibent/vibent-back
  CONTAINER_IMAGE: ${CONTAINER_URL}${CONTAINER_PATH}
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
- build
- dockerize
- deploy-dev
- deploy-prod

build:
  stage: build
  image: maven:3.5.4-jdk-8-alpine
  script:
  - apk add xmlstarlet
  - echo "VERSION=$(xmlstarlet sel -N my=http://maven.apache.org/POM/4.0.0 -t -m my:project -v my:version pom.xml)" > env.sh
  - mvn package -B
  artifacts:
    paths:
    - target/*.jar
    - env.sh

dockerize:
  stage: dockerize
  only:
  - develop
  - /^support\/.+$/
  when: manual
  allow_failure: false
  script:
  - source env.sh
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CONTAINER_URL
  - docker pull $CONTAINER_IMAGE:latest || true
  - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$VERSION --tag $CONTAINER_IMAGE:latest .
  - docker push $CONTAINER_IMAGE:$VERSION
  - docker push $CONTAINER_IMAGE:latest
  dependencies:
  - build

deploy-dev:
  stage: deploy-dev
  only:
  - develop
  - /^support\/.+$/
  script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  - curl -X POST -d "{\"token\":\"$AWS_UTIL_TOKEN\",\"restart\":\"vibent-back-dev\"}" https://admin.vibent.com

deploy-prod:
  stage: deploy-prod
  only:
  - develop
  - /^support\/.+$/
  when: manual
  script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  - curl -X POST -d "{\"token\":\"$AWS_UTIL_TOKEN\",\"restart\":\"vibent-back-prod\"}" https://admin.vibent.com