spring:
  profiles:
    active: local-h2
  jpa:
    hibernate.naming.physical-strategy: com.vibent.vibentback.common.util.VibentDbNamingStrategy
  servlet.multipart.max-file-size: 128KB
  mail:
    host: ssl0.ovh.net
    port: 465
    username: no-reply@vibent.com
    password: '{>[U{:(6m"<NU`h+'
    protocol: smtps
    default-encoding: UTF-8
    properties.mail.smtp:
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
      starttls.enable: true
      starttls.required: true
      ssl.enable: true

vibent:
  auth:
    header:
      key: Authorization
    secret: zCGAq7Yn9NKFQ3GzpYNDDUashbUDeVcbJP59hwc7ANgq2grRX6Xw69nVAHNf8fEy
    issuer: Vibent
    expirationSeconds: 86400 # equivalent to one day
    mock:
      username: vibentUser
      password: $2a$10$cLAIXc2UWiVdSGjxI3Fr5uJUvinj5hBHW1ySIW02.yjrS0DaAvs1O
  aes:
    key: "Qt95J!SaV8DM8^hN"
    ivVector: "xN61SxoGIfdzTWrq"
  aws:
    s3:
      accessKey: AKIAIN5HAIFCOJ2JDY3A
      secretKey: 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
      bucketName: vibent
      bucketBaseUrl: https://s3.eu-west-3.amazonaws.com/vibent/
  client.url: https://dev.vibent.com
  mail.autoConfirm: true
  social.google.clientId: "821632933125-0re06sp9j4l9nurpql79glsfm4k64sai.apps.googleusercontent.com"

spring.jackson.date-format: dd.MM.yyyy

---
### RUN PROFILES
spring:
  profiles: local
  profiles.include: mysql-local, logger

server.port: 8080

---

spring:
  profiles: local-h2
  profiles.include: h2, logger

server.port: 8080

---

spring:
  profiles: dev
  profiles.include: mysql-dev

server.port: 80

---

spring:
  profiles: prod
  profiles.include: mysql-prod

server.port: 80

vibent:
  client.url: https://vibent.com
  social.google.clientId: "634029875861-09kdkppk1khbs7krahm18tcqmggts3ee.apps.googleusercontent.com"

---
### UTILITY DEFINITIONS ###
spring:
  profiles: logger

logging.level:
  org.springframework:
    web.filter.CommonsRequestLoggingFilter: DEBUG
    boot.autoconfigure.security: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: DEBUG
log4j.logger.org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: DEBUG

---
### DATA SOURCE DEFINITIONS ###
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:~/vibent_back
    username: sa
    password: ''
  h2.console.enabled: true

---

spring:
  profiles: mysql-local
  datasource:
    url: jdbc:mysql://127.0.0.1/vibent_back?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=CET
    username: root
    password: root
  jpa:
    show-sql: true

---

spring:
  profiles: mysql-dev
  datasource:
    url: jdbc:mysql://main.cwqlbqunkux0.eu-west-3.rds.amazonaws.com:3306/vibent_back_dev?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=CET
    username: vibent_dev
    password: '9L%b85u^WGLEin7D'

---

spring:
  profiles: mysql-prod
  datasource:
    url: jdbc:mysql://main.cwqlbqunkux0.eu-west-3.rds.amazonaws.com:3306/vibent_back_prod?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=CET
    username: vibent_prod
    password: 'N6^1kr4OwItUoK4#'

---