# Default config

spring.jpa.hibernate.naming.physical-strategy: com.vibent.vibentback.config.VibentPhysicalNamingStrategy

spring:
  datasource:
      url: jdbc:mysql://localhost/VIBENT_BACK?useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: root

---
# Deployed config
spring:
  profiles: prod

  datasource:
      url: #fill in
      username: #fill
      password: #fill


---