# Default config
spring.jpa.hibernate.naming.physical-strategy: com.vibent.vibentback.config.VibentPhysicalNamingStrategy
spring.jpa.show-sql: true

# Default data source
spring:
  datasource:
      url: jdbc:mysql://localhost/vibent_back?useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: root

# Logging config
logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: INFO #DEBUG for more info

---
# Deployed config
spring:
  profiles: prod

  datasource:
      url: #fill in
      username: #fill
      password: #fill


---