spring.jpa.hibernate.naming.physical-strategy: com.gitlab.vibent.vibentback.config.VibentPhysicalNamingStrategy

---

spring:
  profiles: local, test

spring:
  datasource:
    url: jdbc:mysql://localhost/VIBENT_BACK?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root

---

spring:
  profiles: memoryDb

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;INIT=RUNSCRIPT FROM './src/main/resources/vibent.sql';DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;TRACE_LEVEL_FIle=4;
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
