spring.jpa.hibernate.naming.physical-strategy: com.gitlab.vibent.vibentback.config.VibentPhysicalNamingStrategy

---
spring:
  profiles: local, datatest

spring:
  datasource:
    url: jdbc:mysql://localhost/VIBENT_BACK?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root

---
spring:
  profiles: test

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;INIT=RUNSCRIPT FROM './db/vibent.sql';
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
