spring.profiles.active: local

# All envs
spring:
  jpa:
    hibernate.naming.physical-strategy: com.vibent.vibentback.common.util.VibentDbNamingStrategy
  mail:
    #SSL/TLS
#    host: ssl0.ovh.net
#    port: 993
#    username: no-reply@vibent.com
#    password: vibentnoreply
#    protocol: smtp
#    default-encoding: UTF-8
#    properties.mail.smtp:
#      connectiontimeout: 5000
#      timeout: 3000
#      writetimeout: 5000
#      auth: true
#      starttls.enable: true
    host: smtp.gmail.com
    port: 587
    username: test.mail.conor@gmail.com
    password: rootroot
    protocol: smtp
    default-encoding: UTF-8
    properties.mail.smtp:
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
      auth: true
      starttls.enable: true
      starttls.required: true


vibent:
  auth:
    header:
      key: Authorization
    secret: zCGAq7Yn9NKFQ3GzpYNDDUashbUDeVcbJP59hwc7ANgq2grRX6Xw69nVAHNf8fEy
    issuer: Vibent
    expirationSeconds: 86400 # equivalent to one day
    mock:
      username: vibentUser
      password: $2a$10$cLAIXc2UWiVdSGjxI3Fr5uJUvinj5hBHW1ySIW02.yjrS0DaAvs1O
  config:
    groupInviteTokenExpiration: 604800 # equivalent to one week
    confirmMailTokenExpiration: 604800 # equivalent to one week
  aws:
    s3:
      accessKey: AKIAIN5HAIFCOJ2JDY3A
      secretKey: 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
      bucketName: vibent

spring.jackson.date-format: dd.MM.yyyy


---

# Profile for GitlabCI
spring:
  profiles: gitlab-ci
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${java.io.tmpdir}/database/vibent_back;AUTO_SERVER=TRUE
    username: user
    password: pass

vibent.client.url: http://ec2-35-180-98-237.eu-west-3.compute.amazonaws.com
vibent.mail.autoConfirm: true

---

# Profile for Conors AWS Dev Server
spring:
  profiles: conor-aws

  datasource:
    url: jdbc:mysql://main.cwqlbqunkux0.eu-west-3.rds.amazonaws.com:3306/vibent_back?useUnicode=yes&characterEncoding=UTF-8
    username: Main
    password: '&5t7cvREx*5&b^v9'

server.port: 8080

vibent.client.url: http://ec2-35-180-98-237.eu-west-3.compute.amazonaws.com
vibent.mail.autoConfirm: true

---

# Local configuration
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/vibent_back?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true

vibent.client.url: http://ec2-35-180-98-237.eu-west-3.compute.amazonaws.com
vibent.mail.autoConfirm: true

logging.level:
  org.springframework:
    web.filter.CommonsRequestLoggingFilter: DEBUG
    boot.autoconfigure.security: INFO
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: DEBUG

log4j.logger.org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: DEBUG

---